### ISSUE TITLE
Support for multiple OFDS data formats as data input to tool

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#1]
## User story to be addressed

As a Data user, I need to be able to convert my OFDS data to the appropriate format in order to upload it to the tool.

## Issue for tool

OFDS data can be produced and considered valid as JSON, GeoJSON or CSV. Either users of the tool will need to provide data in one of these formats as specified, or the tool must be able to support all three.

There is an existing conversion tool, [CoVE](https://ofds.cove.opendataservices.coop/) that already allows OFDS data to be converted from one of these three to either of the other.

**Comment by rhiaro** [comment]
The tool will be restricted to geoJSON input, but we can point users to the conversion tool in the docs.

**Comment by R2ZER0** [comment]
That's a point, if we require GeoJSON input, and the only conversion tool is an online server which requires upload, does it still count as being an offline tool?

**Comment by odscjen** [comment]
CoVE is also available as a command line tool (https://libcoveofds.readthedocs.io/en/latest/index.html) which can be used offline so I think this still counts as being an offline tool?

**Comment by odscjen** [comment]
CoVE is linked to in the documentation, so closing this issue
