### ISSUE TITLE
Retaining all network operator details for each span, regardless of its duplication status

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#10]
## User stories to be addressed

1. As a Network operator, I need data that shows who owns existing fibres in my region of interest so I know who to approach about leasing lit capacity or dark fibre from.

2. As a Policy maker, I need data that shows who owns existing fibres in my region of interest and who merely leases capacity, so I can judge bids for service supply and if they’re coming from the owner or a fibre or a leaser.

## Issue for the tool

Multiple operators may be using the same fibre/cable within their own networks. When deduplicating to consolidate down to the actual physical infrastructure, the information about who is operating on each fibre/cable should not be lost.

## For discussion

how to retain the details of the network operator for each span, even if it has been identified as likely to be a duplicate?

**Comment by rhiaro** [comment]
Related: https://github.com/Open-Telecoms-Data/ofds_consolidation_tool/issues/23

**Comment by rhiaro** [comment]
The tool retrains the network operator details
