### ISSUE TITLE
Route accuracy and its incorporation into the  likelihood of a pair of spans being duplicates

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#11]
## User story to be addressed

As a Civil engineer, I need an estimate of confidence that I have identified the existing fibres, and their accurate routes, within my region of interest so that I can plan my construction projects.

## Issue for the tool

OFDS offers the ability to record a fibre span (i.e. the route between two nodes) to whatever level of accuracy the data creator wishes to use. This could be high accuracy, e.g. a multi-line with coordinates given to 6 decimal places, or it could be low accuracy, e.g. a single line with coordinates given to 1 decimal place.

## For discussion

Given that the accuracy of the input data will be outside of the tools control, to what extent should this be incorporated into the tools function? 
Should the accuracy of the data be used to help calculate the likelihood of duplication? 
Should the tool recalibrate all input data to the same level of accuracy? 
How will the tool account for different levels of accuracy in the input datasets?

**Comment by rhiaro** [comment]
Where accuracy details are present in the original data, we can use this value to weigh the score when comparing the two sets of coordinates. ie. if two sets of coordinates seem close enough to tell the user they're probably the same, but the accuracy of one of the datsets is `low`, we can reduce the confidence value; or vice versa if it's `high`.

> Should the tool recalibrate all input data to the same level of accuracy?

I don't think this would be helpful; we'd be reducing to lowest common denominator.

> How will the tool account for different levels of accuracy in the input datasets?

Through the supervised part, I think. We can flag to the user when data is labelled as inaccurate, and let them make the decision.

**Comment by rhiaro** [comment]
After conversation today - "accuracy" and "number of decimal places of coordinates" are not necessarily correlated

**Comment by rhiaro** [comment]
Closing, as out of scope for this tool. The output is only going to be as accurate as the input - data quality needs to be addressed elsewhere.
