### ISSUE TITLE
Options for merging datasets

### ISSUE THREAD

**Issue by rhiaro** [Open-Telecoms-Data/ofds_consolidation_tool#17]
Simplest is to ask the user to pick one to retain (all data from network A, or all data from network B, no merging/combining).

Set the option for the whole network, or allow user to choose per node/span?

More complicated, so determine if this is useful enough:

* Fill in missing data from one network which is present in the other network (always? sometimes? depends on field? ask user?)
* Merge fields which are amenable to being merged, eg. arrays (always? sometimes? depends? ask?)
* How to combine fields which are single values? (depends? ask?)

**Comment by R2ZER0** [comment]
I'm thinking, for a simple first implementation, of allowing the user to choose which node/span info to keep whenever they decide as duplicate? E.g. three buttons "Keep A"  "Keep Both"  "Keep B"

**Comment by rhiaro** [comment]
Discussion with @R2ZER0 and @odscjen:

We should combine arrays in the consolidated output for:

* `networkProviders`
* `technologies`
* `transmissionMedium`
* `internationalConnections`

If we're saying this is one cable, these make sense to merge.
