### ISSUE TITLE
Hotlinking to open street map

### ISSUE THREAD

**Issue by rhiaro** [Open-Telecoms-Data/ofds_consolidation_tool#19]
At the moment the prototype pulls map tiles from the web. At some point we need to work out how to make sure this will work fully offline.

Related: #3, #4

**Comment by R2ZER0** [comment]
To work fully offline, we could either:
* Find some existing offline map implementation / plugin for QGIS
* Download a very high-level (lo-res) set of OSM tiles, package them with our plugin
* Give the option to disable the background map ("offline mode")

**Comment by rhiaro** [comment]
We discussed this last week and concluded that documenting that the background map will not be available when used offline (but the tool will still work) is sufficient for this version.
