### ISSUE TITLE
Methodology of duplication judgement

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#2]
## User stories to be addressed

As a Network operator/Policy maker, I need to be able to explain the providence and methodology used to decide if two routes are duplicate, to justify any business case I make as a result.

## Issue for tool

Users will need to be able to understand how the tool has come to any consolidation decisions or recommendations, this tool cannot be a black-box. This can be dealt with through appropriate documentation of the methodology the tool will follow.

## For discussion

To what extent will the tool follow an automated methodology vs asking the user to supervise the process, making decisions as they go?

**Comment by rhiaro** [comment]
Related: #16, #18

**Comment by rhiaro** [comment]
Currently we have configuration for setting the confidence threshold over which to automatically merge, and under which to automatically not merge (without asking). Everything in between gets run by the user.

**Comment by rhiaro** [comment]
The [scoring is documented here](https://open-telecoms-data.github.io/ofds_consolidation_tool/howto.html#scoring) at a high level, and commented in the code in much more detail. The fields which matched are in the provenance data output, as rationale for the overall score, when two features were merged. Whether or not the merge was done automatically or manually is also in the provenance output.
