### ISSUE TITLE
Write docs for how to go from QGIS output to other useful formats

### ISSUE THREAD

**Issue by rhiaro** [Open-Telecoms-Data/ofds_consolidation_tool#36]
How can the user export the output of consolidation tool to share the result with other people? Eg. output to PDF, web compatible map. Related to #35

**Comment by odscjen** [comment]
I don't think we need this, this is out of scope and would essentially just be pointing out to users that they can use QGIS or any other suitable piece of software to manipulate the output as they see fit. This should (hopefully) be obvious! We've told them that the output is geoJSON files saved locally to their computer, I think this is enough
