### ISSUE TITLE
Documentation and privacy statement

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#4]
## User stories to be addressed

1. As a Data user, I require clear documentation to ensure I can use the tool correctly.

2. User tracking statement and privacy notice.

## Issue for tool

Ensure the tool is fully documented. The user tracking statement and privacy notice is dependent on the outcome of https://github.com/Open-Telecoms-Data/ofds_consolidation_tool/issues/3, an offline tool should not need these things.

**Comment by rhiaro** [comment]
It's probably worth bundling a privacy statement with the tool that confirms that no data is sent or retrieved over the web from the tool.

We should also think about whether we're publishing the docs online, or bundling them with the tool (or both).
