### ISSUE TITLE
tool data output format that can be read by most GIS

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#5]
## User story to be addressed

As a Data user, I require data in an output format that can be directly loaded into a GIS system.

## Issue for tool

As data with a significant spatial component most users of network data need to be able to interact with it using a GIS.

## For discussion

What format should the tool offer as output data?

**Comment by rhiaro** [comment]
OFDS GeoJSON output is generic, we'll use that.
