### ISSUE TITLE
Retention of input metadata in output dataset

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#6]
## User story to be addressed

As a Data user, I require information on the date the input data was created.

## Issue for tool

If the tool is outputting a single dataset, it would be useful to users if it retained a certain amount of the metadata associated with the input datasets. Date of creation is particularly important for helping to judge how up-to-date the input data may have been.

## For discussion

Which pieces of input metadata should be retained in the tool output and how should they be formatted?

**Comment by rhiaro** [comment]
Related: #18

**Comment by rhiaro** [comment]
Related: https://github.com/Open-Telecoms-Data/ofds_consolidation_tool/issues/23

**Comment by rhiaro** [comment]
Any network metadata that was input is retained in the output in the same format
