### ISSUE TITLE
Gauging the likelihood of a pair of fibres from different input datasets being duplicates

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#7]
## User story to be addressed

As a Data user, I require a tool that allows me to gauge the likelihood of a duplicate fibre, so that I can decide whether to treat it as such as the situation depends.

## Issue for the tool

Due to the likely quality of the data available it is unlikely that across a consolidated dataset of multiple networks there will be many spans that can be classified as 100% definitely duplicates of each other. Therefore the tool needs to be able to provide recommendations on how likely it is that any two spans are duplicates.

## For discussion

What fields within OFDS can be used to gauge the likelihood of duplication across multiple input datasets? Are there any parameters or boundaries that can be used to assign a figure to the likelihood?

**Comment by rhiaro** [comment]
#16
