### ISSUE TITLE
Recalculating fibre property values as part of output consolidated dataset

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#8]
## User stories to be addressed

1. As a Policy maker, I need data that shows total capacity on existing fibres in my region of interest so I can track connection resilience.

2. As a Network operator, I need data that shows total capacity on existing fibres in my region of interest so I can decide if I should lay my own fibres or if there is sufficient capacity to lease.

## Issue for the tool

OFDS data can record the capacity on a span. Without deduplicating the spans however, if a user was just to add up all the given capacity values the spans in a consolidated dataset they run the risk of overcounting.

## For discussion

To what extent should the consolidated output dataset consolidate all field values? 
What if one of the input datasets is missing this information? 
Which fields should be recalculated as part of the output dataset?

**Comment by rhiaro** [comment]
In OFDS, the `capacity` value:

> For spans with multiple network providers, the sum of the capacity of each provider’s network on this span

So as there is no breakdown of the capacity of each network by provider, I don't think there's anything we can do other than just the deduplication (which the tool does) to solve this. When two spans with different providers are consolidated, the capacity value is summed.
