### ISSUE TITLE
Output consolidated data to focus on the individual fibres/cables as the primary data

### ISSUE THREAD

**Issue by odscjen** [Open-Telecoms-Data/ofds_consolidation_tool#9]
## User stories to be addressed

1. As a Policy maker, I need data that shows existing fibres in my region of interest so I can track connection resilience.

2. As a Policy maker, I need data that shows existing fibres in my region of interest so I can decide where to place new infrastructure that would benefit from fibre connectivity.

3. As a Policy maker, I need data that shows the existing fibres in my region of interest to spot if there are gaps that need to be filled.

4. As a Network operator, I need data that shows existing fibres in my region of interest so I can decide if I should lay my own fibres.

## Issue for the tool

Combining multiple network maps doesn't make it clear how many actual fibres/cables there are along a route. Multiple networks can use the same fibre/cable. The tool must provide some kind of indication of which spans are duplicated across the multiple inputs. This issue is very closely related to #7 

## For discussion

See #7

**Comment by rhiaro** [comment]
The output data from the tool will show which spans have been consolidated, ie. were duplicates in the input
